spring:
  application:
    name: ssl-client

server:
  port: 7778

request:
  #读超时时间，单位为ms
  read-timeout: 15000
  #连接超时时间，单位为ms
  connect-timeout: 15000
  #一次最多接收MaxTotal次请求
  max-total: 200
  #每次能并行接收的请求数量
  max-per-route: 200
  type: https
  # true：GM SSL,false：rsa
  is-gm: true
  # SSL密钥更新时间（单位：小时）
  ssl-key-update-hours: 8
  two-way:
    #双向认证,客户端验证服务端,enabled:启用，disabled:停用
    enabled: enabled
    #客户端证书
    client-p12-path: /persistent/disk/workspace/001-java/003-work/ssl/ssl-server/ssl-client/ssl/keystore.p12
    #根证书信任链
    ca-keystore-path: /persistent/disk/workspace/001-java/003-work/ssl/ssl-server/ssl-client/ssl/truststore.p12
    #客户端证书密码
    key-storepass: 123456
    #根证书链密码,没有密码设置为nopassword
    trust-store-password: 123456


logging:
  level:
    root: info